### ISSUE TITLE
Removal of mapping types

### ISSUE THREAD

**Issue by jetnet** [Norconex/committer-elasticsearch#39] opened 2019-06-27 07:30 UTC
Document type is obsolete in 7.x and will be removed in 8.x: https://www.elastic.co/guide/en/elasticsearch/reference/7.x/removal-of-types.html

Could you please make the parameter `<typeName>` optional?
Thanks!

**Comment by essiembre** [comment] 2019-06-27 22:40
Already done. Duplicate of #37.

**Closed by essiembre** 2019-06-27 22:40 UTC
Labels: duplicate
